### ISSUE TITLE
Expose celery tasks

### ISSUE THREAD

**Issue by sooraj1002** [BharatSahAIyak/autotune#120]
## TASK

We need to expose the celery tasks which are pending for:

- [ ] Dataset generation @Zolo-ryan
- [ ] Training @sooraj1002 
- [ ] Model Deployment @sooraj1002 
- [ ] All scheduled tasks @sooraj1002 

### REQUEST HEADERS

- `user-id`
- `role`
[validation already handled in UserIdMixin]

### RESPONSE

```json
{
    "queued": [
        {
            "taskId": "CELERY_TASK_ID",
            "task_type": "infer from the task_name",
            "taskName": "task_name(from the Task Model)",
            "user": "user_id for user who created it",
            "taskArgs": "Expose using celery"
        },
        {
            "taskId": "CELERY_TASK_ID",
            "task_type": "infer from the task_name",
            "taskName": "task_name(from the Task Model)",
            "user": "user_id for user who created it",
            "taskArgs": "Expose using celery"
        }
    ],
    "scheduled": [
        {
            "taskId": "CELERY_TASK_ID",
            "task_type": "infer from the task_name",
            "taskName": "task_name(from the Task Model)",
            "user": "user_id for user who created it",
            "taskArgs": "Expose using celery",
            "scheduled_for": "Time in IST"
        },
        {
            "taskId": "CELERY_TASK_ID",
            "task_type": "infer from the task_name",
            "taskName": "task_name(from the Task Model)",
            "user": "user_id for user who created it",
            "taskArgs": "Expose using celery",
            "scheduled_for": "Time in IST"
        }
    ]
}
```

**Comment by ranjanmangla1** [comment]
hey @sooraj1002 , can I take this issue? I already have a lot of experience working with dramatiq (it is very close to celery)

**Comment by sooraj1002** [comment]
Sure. have assigned the ticket
